### ISSUE TITLE
[BUG] 使用系统文件选择发送的图片闪退

### ISSUE THREAD

**Issue by suzhelan** [suzhelan/TimTool#16]
TIM版本（无效的版本 或 带有最新版字样 将会被关闭）：
4.0.98
模块版本：
1.7
清晰的描述你所遇到的问题（带上视频/图片/日志）难以排查或无效的反馈信息将会被关闭：  
- [x] 开发人员已成功复现 推测是在releaes出现的问题  
---
一加13，coloros15.305
a15，使用系统文件，系统相册等功能点击闪退
```
Crash unexpectedly: java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.tencent.tim/top.sacz.timtool.ui.activity.a}: java.lang.InstantiationException: java.lang.Class<top.sacz.timtool.ui.activity.a> cannot be instantiated
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4255)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4569)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:126)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:114)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:86)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2902)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:282)
	at android.os.Looper.loop(Looper.java:387)
	at android.app.ActivityThread.main(ActivityThread.java:9501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1005)
Caused by: java.lang.InstantiationException: java.lang.Class<top.sacz.timtool.ui.activity.a> cannot be instantiated
	at java.lang.Class.newInstance(Native Method)
	at J2.b.newActivity(SourceFile:5)
	at com.tencent.biz.richframework.hook.instrumentation.HookedInstrumentation.newActivity(P:3)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4242)
	... 13 more
```

**Comment by HdShare** [comment]
可通过混淆配置
```
-keep class top.sacz.timtool.ui.activity.ChooseAgentActivity {*;}
```
初步解决以上问题

**Comment by suzhelan** [comment]
跟踪进度 开启雪花飘落时 如果启动了ChooseAgentActivity会导致雪花飘落在没有root view 的Activity上 导致崩溃
